### ISSUE TITLE
Unspecified output 

### ISSUE THREAD

**Issue by GoldenHamed** [hadipourh/autoguess#3]
Hello Mr. Hadipour, 
The output of some commands does not match your README.md file.
For example 4, which uses algebraic relations, when I execute the commands, the output is not the same as your output. For example, I have attached the output of the command for you.
[algeb_relation.txt](https://github.com/hadipourh/autoguess/files/11478711/algeb_relation.txt)

 Thank you in advance

**Comment by hadipourh** [comment]
Hi Hamed,

 What you have observed is completely normal!
The reason for the discrepancy lies in running the tool with different input arguments. 
It is important to note that `maxguess` sets the upper bound for the size of the guess basis. Please refer to our paper to see more details. 

In your initial attempt, you received `UNSAT` because you restricted the size of the guess basis to `<= 1`, whereas the minimum size of the guess basis, in this case, is 2. As a result, the tool correctly returned `UNSAT`, indicating that there is no guess basis of size `<= 2` available.

During your second attempt, you ran the tool with `maxguess <= 4`, resulting in a guess basis of size 4. This outcome is entirely normal.

Even if you run exactly the same command as I did on my machine, it is still normal if you get a different guess basis, because SAT/MILP/SMT solvers do not employ entirely deterministic algorithms, and there might be many solutions with the same property for the same problem. For example, there might be a 100 guess bases of size 4 for the same guess-and-determine problem. However, the minimal guess basis size is an invariant parameter of the solutions.

I hope my explanation addresses your concern. For more detailed information, I encourage you to refer to our paper.

Another important point to consider is that when using SAT/SMT, Autoguess constructs and solves satisfiability problems that fulfill the given input conditions. In this scenario, if you use `--maxguess 4` in the input command, it means the size of guess basis should be at most 4. So, if the tool returns a guess basis of size 1, 2, or 3, it is within the expected behavior. However, obtaining a guess basis larger than 4, in this case, would indicate a potential bug in the tool.

On the other hand, when employing MILP/CP or Groebner basis, Autoguess formulates and solves an optimization problem to discover a minimal guess basis that satisfies the input conditions. This case seems more attractive but of course, it is a harder problem and thus more time-consuming.

Finally, I hope you enjoy the tool ;-)

**Comment by GoldenHamed** [comment]
Thank you for your response.
